-- Seed the marketplace catalog for the storefront homepage: everyday
-- Cebu produce across real categories with fixed sellable variants,
-- market-scoped standard prices, and Cebu Central availability. Row
-- inserts only; no schema change. Slugs map to the public produce
-- image library consumed by apps/web presentation.

INSERT OR IGNORE INTO category (id, code, name, slug, status, sort_order, created_at, updated_at)
VALUES
  ('category-fresh-fruits', 'FRESH_FRUITS', 'Fruits', 'fruits', 'active', 2, 0, 0),
  ('category-vegetables', 'VEGETABLES', 'Vegetables', 'vegetables', 'active', 3, 0, 0),
  ('category-leafy-greens', 'LEAFY_GREENS', 'Leafy greens', 'leafy-greens', 'active', 4, 0, 0),
  ('category-pantry', 'PANTRY', 'Pantry', 'pantry', 'active', 5, 0, 0);

INSERT OR IGNORE INTO inventory_pool (id, product_id, base_unit_id, sourcing_mode, created_at, updated_at)
VALUES
  ('pool-avocado', 'product-avocado', 'unit-gram', 'HYBRID', 0, 0),
  ('pool-banana-lakatan', 'product-banana-lakatan', 'unit-gram', 'HYBRID', 0, 0),
  ('pool-mango-carabao', 'product-mango-carabao', 'unit-gram', 'HYBRID', 0, 0),
  ('pool-strawberry', 'product-strawberry', 'unit-gram', 'HYBRID', 0, 0),
  ('pool-pineapple', 'product-pineapple', 'unit-gram', 'HYBRID', 0, 0),
  ('pool-watermelon', 'product-watermelon', 'unit-gram', 'HYBRID', 0, 0),
  ('pool-calamansi', 'product-calamansi', 'unit-gram', 'HYBRID', 0, 0),
  ('pool-papaya', 'product-papaya', 'unit-gram', 'HYBRID', 0, 0),
  ('pool-tomato', 'product-tomato', 'unit-gram', 'HYBRID', 0, 0),
  ('pool-carrot', 'product-carrot', 'unit-gram', 'HYBRID', 0, 0),
  ('pool-broccoli', 'product-broccoli', 'unit-gram', 'HYBRID', 0, 0),
  ('pool-cucumber', 'product-cucumber', 'unit-gram', 'HYBRID', 0, 0),
  ('pool-cabbage', 'product-cabbage', 'unit-gram', 'HYBRID', 0, 0),
  ('pool-eggplant', 'product-eggplant', 'unit-gram', 'HYBRID', 0, 0),
  ('pool-kangkong', 'product-kangkong', 'unit-gram', 'HYBRID', 0, 0),
  ('pool-pechay', 'product-pechay', 'unit-gram', 'HYBRID', 0, 0),
  ('pool-garlic', 'product-garlic', 'unit-gram', 'HYBRID', 0, 0);

INSERT OR IGNORE INTO product (id, category_id, inventory_pool_id, slug, name, description, status, created_at, updated_at)
VALUES
  ('product-avocado', 'category-fresh-fruits', 'pool-avocado', 'avocado', 'Creamy Avocado', 'Rich Cebu-grown avocados selected for salads, toast, and smoothies.', 'active', 0, 0),
  ('product-banana-lakatan', 'category-fresh-fruits', 'pool-banana-lakatan', 'banana-lakatan', 'Lakatan Bananas', 'Sweet, fragrant Lakatan bananas packed at an everyday family size.', 'active', 0, 0),
  ('product-mango-carabao', 'category-fresh-fruits', 'pool-mango-carabao', 'mango-carabao', 'Carabao Mangoes', 'Golden Philippine mangoes with a bright aroma and smooth sweetness.', 'active', 0, 0),
  ('product-strawberry', 'category-fresh-fruits', 'pool-strawberry', 'strawberry', 'Baguio Strawberries', 'Fresh strawberries for breakfast bowls, baking, and snacks.', 'active', 0, 0),
  ('product-pineapple', 'category-fresh-fruits', 'pool-pineapple', 'pineapple', 'Sweet Pineapple', 'A bright tropical pineapple with a juicy, balanced finish.', 'active', 0, 0),
  ('product-watermelon', 'category-fresh-fruits', 'pool-watermelon', 'watermelon', 'Seedless Watermelon', 'Crisp, hydrating watermelon for sharing and chilled desserts.', 'active', 0, 0),
  ('product-calamansi', 'category-fresh-fruits', 'pool-calamansi', 'calamansi', 'Calamansi', 'Bright local citrus for drinks, sauces, and marinades.', 'active', 0, 0),
  ('product-papaya', 'category-fresh-fruits', 'pool-papaya', 'papaya', 'Solo Papaya', 'Sweet orange-fleshed papaya selected for breakfast and dessert.', 'active', 0, 0),
  ('product-tomato', 'category-vegetables', 'pool-tomato', 'tomato', 'Roma Tomatoes', 'Firm tomatoes suited to sauces, salads, and everyday cooking.', 'active', 0, 0),
  ('product-carrot', 'category-vegetables', 'pool-carrot', 'carrot', 'Highland Carrots', 'Crunchy carrots with a naturally sweet finish.', 'active', 0, 0),
  ('product-broccoli', 'category-vegetables', 'pool-broccoli', 'broccoli', 'Fresh Broccoli', 'Tender green florets ideal for roasting, steaming, and stir-fries.', 'active', 0, 0),
  ('product-cucumber', 'category-vegetables', 'pool-cucumber', 'cucumber', 'Japanese Cucumber', 'Crisp, thin-skinned cucumbers for salads and pickles.', 'active', 0, 0),
  ('product-cabbage', 'category-vegetables', 'pool-cabbage', 'cabbage', 'Baguio Cabbage', 'Tightly packed cabbage for soups, slaws, and stir-fries.', 'active', 0, 0),
  ('product-eggplant', 'category-vegetables', 'pool-eggplant', 'eggplant', 'Purple Eggplant', 'Glossy local eggplant for grilling, stews, and tortang talong.', 'active', 0, 0),
  ('product-kangkong', 'category-leafy-greens', 'pool-kangkong', 'kangkong', 'Fresh Kangkong', 'Tender water spinach bundled for soups and quick sautes.', 'active', 0, 0),
  ('product-pechay', 'category-leafy-greens', 'pool-pechay', 'pechay', 'Native Pechay', 'Fresh leafy pechay for soups, noodles, and quick stir-fries.', 'active', 0, 0),
  ('product-garlic', 'category-pantry', 'pool-garlic', 'garlic', 'Native Garlic', 'Fragrant native garlic with bold flavor for Filipino cooking.', 'active', 0, 0);

INSERT OR IGNORE INTO sku (id, product_id, code, name, sellable_unit_id, consumption_base_quantity, status, sort_order, created_at, updated_at)
VALUES
  ('sku-avocado-250g', 'product-avocado', 'AVOCADO_250G', '250 g', 'unit-gram', 250, 'active', 1, 0, 0),
  ('sku-avocado-500g', 'product-avocado', 'AVOCADO_500G', '500 g', 'unit-gram', 500, 'active', 2, 0, 0),
  ('sku-avocado-1kg', 'product-avocado', 'AVOCADO_1KG', '1 kg', 'unit-kilogram', 1000, 'active', 3, 0, 0),
  ('sku-banana-lakatan-250g', 'product-banana-lakatan', 'BANANA_LAKATAN_250G', '250 g', 'unit-gram', 250, 'active', 1, 0, 0),
  ('sku-banana-lakatan-500g', 'product-banana-lakatan', 'BANANA_LAKATAN_500G', '500 g', 'unit-gram', 500, 'active', 2, 0, 0),
  ('sku-banana-lakatan-1kg', 'product-banana-lakatan', 'BANANA_LAKATAN_1KG', '1 kg', 'unit-kilogram', 1000, 'active', 3, 0, 0),
  ('sku-mango-carabao-250g', 'product-mango-carabao', 'MANGO_CARABAO_250G', '250 g', 'unit-gram', 250, 'active', 1, 0, 0),
  ('sku-mango-carabao-500g', 'product-mango-carabao', 'MANGO_CARABAO_500G', '500 g', 'unit-gram', 500, 'active', 2, 0, 0),
  ('sku-mango-carabao-1kg', 'product-mango-carabao', 'MANGO_CARABAO_1KG', '1 kg', 'unit-kilogram', 1000, 'active', 3, 0, 0),
  ('sku-strawberry-250g', 'product-strawberry', 'STRAWBERRY_250G', '250 g', 'unit-gram', 250, 'active', 1, 0, 0),
  ('sku-strawberry-500g', 'product-strawberry', 'STRAWBERRY_500G', '500 g', 'unit-gram', 500, 'active', 2, 0, 0),
  ('sku-strawberry-1kg', 'product-strawberry', 'STRAWBERRY_1KG', '1 kg', 'unit-kilogram', 1000, 'active', 3, 0, 0),
  ('sku-pineapple-250g', 'product-pineapple', 'PINEAPPLE_250G', '250 g', 'unit-gram', 250, 'active', 1, 0, 0),
  ('sku-pineapple-500g', 'product-pineapple', 'PINEAPPLE_500G', '500 g', 'unit-gram', 500, 'active', 2, 0, 0),
  ('sku-pineapple-1kg', 'product-pineapple', 'PINEAPPLE_1KG', '1 kg', 'unit-kilogram', 1000, 'active', 3, 0, 0),
  ('sku-watermelon-250g', 'product-watermelon', 'WATERMELON_250G', '250 g', 'unit-gram', 250, 'active', 1, 0, 0),
  ('sku-watermelon-500g', 'product-watermelon', 'WATERMELON_500G', '500 g', 'unit-gram', 500, 'active', 2, 0, 0),
  ('sku-watermelon-1kg', 'product-watermelon', 'WATERMELON_1KG', '1 kg', 'unit-kilogram', 1000, 'active', 3, 0, 0),
  ('sku-calamansi-250g', 'product-calamansi', 'CALAMANSI_250G', '250 g', 'unit-gram', 250, 'active', 1, 0, 0),
  ('sku-calamansi-500g', 'product-calamansi', 'CALAMANSI_500G', '500 g', 'unit-gram', 500, 'active', 2, 0, 0),
  ('sku-calamansi-1kg', 'product-calamansi', 'CALAMANSI_1KG', '1 kg', 'unit-kilogram', 1000, 'active', 3, 0, 0),
  ('sku-papaya-250g', 'product-papaya', 'PAPAYA_250G', '250 g', 'unit-gram', 250, 'active', 1, 0, 0),
  ('sku-papaya-500g', 'product-papaya', 'PAPAYA_500G', '500 g', 'unit-gram', 500, 'active', 2, 0, 0),
  ('sku-papaya-1kg', 'product-papaya', 'PAPAYA_1KG', '1 kg', 'unit-kilogram', 1000, 'active', 3, 0, 0),
  ('sku-tomato-250g', 'product-tomato', 'TOMATO_250G', '250 g', 'unit-gram', 250, 'active', 1, 0, 0),
  ('sku-tomato-500g', 'product-tomato', 'TOMATO_500G', '500 g', 'unit-gram', 500, 'active', 2, 0, 0),
  ('sku-tomato-1kg', 'product-tomato', 'TOMATO_1KG', '1 kg', 'unit-kilogram', 1000, 'active', 3, 0, 0),
  ('sku-carrot-250g', 'product-carrot', 'CARROT_250G', '250 g', 'unit-gram', 250, 'active', 1, 0, 0),
  ('sku-carrot-500g', 'product-carrot', 'CARROT_500G', '500 g', 'unit-gram', 500, 'active', 2, 0, 0),
  ('sku-carrot-1kg', 'product-carrot', 'CARROT_1KG', '1 kg', 'unit-kilogram', 1000, 'active', 3, 0, 0),
  ('sku-broccoli-250g', 'product-broccoli', 'BROCCOLI_250G', '250 g', 'unit-gram', 250, 'active', 1, 0, 0),
  ('sku-broccoli-500g', 'product-broccoli', 'BROCCOLI_500G', '500 g', 'unit-gram', 500, 'active', 2, 0, 0),
  ('sku-broccoli-1kg', 'product-broccoli', 'BROCCOLI_1KG', '1 kg', 'unit-kilogram', 1000, 'active', 3, 0, 0),
  ('sku-cucumber-250g', 'product-cucumber', 'CUCUMBER_250G', '250 g', 'unit-gram', 250, 'active', 1, 0, 0),
  ('sku-cucumber-500g', 'product-cucumber', 'CUCUMBER_500G', '500 g', 'unit-gram', 500, 'active', 2, 0, 0),
  ('sku-cucumber-1kg', 'product-cucumber', 'CUCUMBER_1KG', '1 kg', 'unit-kilogram', 1000, 'active', 3, 0, 0),
  ('sku-cabbage-250g', 'product-cabbage', 'CABBAGE_250G', '250 g', 'unit-gram', 250, 'active', 1, 0, 0),
  ('sku-cabbage-500g', 'product-cabbage', 'CABBAGE_500G', '500 g', 'unit-gram', 500, 'active', 2, 0, 0),
  ('sku-cabbage-1kg', 'product-cabbage', 'CABBAGE_1KG', '1 kg', 'unit-kilogram', 1000, 'active', 3, 0, 0),
  ('sku-eggplant-250g', 'product-eggplant', 'EGGPLANT_250G', '250 g', 'unit-gram', 250, 'active', 1, 0, 0),
  ('sku-eggplant-500g', 'product-eggplant', 'EGGPLANT_500G', '500 g', 'unit-gram', 500, 'active', 2, 0, 0),
  ('sku-eggplant-1kg', 'product-eggplant', 'EGGPLANT_1KG', '1 kg', 'unit-kilogram', 1000, 'active', 3, 0, 0),
  ('sku-kangkong-250g', 'product-kangkong', 'KANGKONG_250G', '250 g', 'unit-gram', 250, 'active', 1, 0, 0),
  ('sku-kangkong-500g', 'product-kangkong', 'KANGKONG_500G', '500 g', 'unit-gram', 500, 'active', 2, 0, 0),
  ('sku-kangkong-1kg', 'product-kangkong', 'KANGKONG_1KG', '1 kg', 'unit-kilogram', 1000, 'active', 3, 0, 0),
  ('sku-pechay-250g', 'product-pechay', 'PECHAY_250G', '250 g', 'unit-gram', 250, 'active', 1, 0, 0),
  ('sku-pechay-500g', 'product-pechay', 'PECHAY_500G', '500 g', 'unit-gram', 500, 'active', 2, 0, 0),
  ('sku-pechay-1kg', 'product-pechay', 'PECHAY_1KG', '1 kg', 'unit-kilogram', 1000, 'active', 3, 0, 0),
  ('sku-garlic-250g', 'product-garlic', 'GARLIC_250G', '250 g', 'unit-gram', 250, 'active', 1, 0, 0),
  ('sku-garlic-500g', 'product-garlic', 'GARLIC_500G', '500 g', 'unit-gram', 500, 'active', 2, 0, 0),
  ('sku-garlic-1kg', 'product-garlic', 'GARLIC_1KG', '1 kg', 'unit-kilogram', 1000, 'active', 3, 0, 0);

INSERT OR IGNORE INTO price_version (id, sku_id, market_id, price_type, currency, amount_minor, valid_from, version, created_at)
VALUES
  ('price-avocado-250g-v1', 'sku-avocado-250g', 'market-metro-cebu', 'STANDARD', 'PHP', 4725, 0, 1, 0),
  ('price-avocado-500g-v1', 'sku-avocado-500g', 'market-metro-cebu', 'STANDARD', 'PHP', 9450, 0, 1, 0),
  ('price-avocado-1kg-v1', 'sku-avocado-1kg', 'market-metro-cebu', 'STANDARD', 'PHP', 18900, 0, 1, 0),
  ('price-banana-lakatan-250g-v1', 'sku-banana-lakatan-250g', 'market-metro-cebu', 'STANDARD', 'PHP', 3675, 0, 1, 0),
  ('price-banana-lakatan-500g-v1', 'sku-banana-lakatan-500g', 'market-metro-cebu', 'STANDARD', 'PHP', 7350, 0, 1, 0),
  ('price-banana-lakatan-1kg-v1', 'sku-banana-lakatan-1kg', 'market-metro-cebu', 'STANDARD', 'PHP', 14700, 0, 1, 0),
  ('price-mango-carabao-250g-v1', 'sku-mango-carabao-250g', 'market-metro-cebu', 'STANDARD', 'PHP', 5950, 0, 1, 0),
  ('price-mango-carabao-500g-v1', 'sku-mango-carabao-500g', 'market-metro-cebu', 'STANDARD', 'PHP', 11900, 0, 1, 0),
  ('price-mango-carabao-1kg-v1', 'sku-mango-carabao-1kg', 'market-metro-cebu', 'STANDARD', 'PHP', 23800, 0, 1, 0),
  ('price-strawberry-250g-v1', 'sku-strawberry-250g', 'market-metro-cebu', 'STANDARD', 'PHP', 8950, 0, 1, 0),
  ('price-strawberry-500g-v1', 'sku-strawberry-500g', 'market-metro-cebu', 'STANDARD', 'PHP', 17900, 0, 1, 0),
  ('price-strawberry-1kg-v1', 'sku-strawberry-1kg', 'market-metro-cebu', 'STANDARD', 'PHP', 35800, 0, 1, 0),
  ('price-pineapple-250g-v1', 'sku-pineapple-250g', 'market-metro-cebu', 'STANDARD', 'PHP', 4125, 0, 1, 0),
  ('price-pineapple-500g-v1', 'sku-pineapple-500g', 'market-metro-cebu', 'STANDARD', 'PHP', 8250, 0, 1, 0),
  ('price-pineapple-1kg-v1', 'sku-pineapple-1kg', 'market-metro-cebu', 'STANDARD', 'PHP', 16500, 0, 1, 0),
  ('price-watermelon-250g-v1', 'sku-watermelon-250g', 'market-metro-cebu', 'STANDARD', 'PHP', 4975, 0, 1, 0),
  ('price-watermelon-500g-v1', 'sku-watermelon-500g', 'market-metro-cebu', 'STANDARD', 'PHP', 9950, 0, 1, 0),
  ('price-watermelon-1kg-v1', 'sku-watermelon-1kg', 'market-metro-cebu', 'STANDARD', 'PHP', 19900, 0, 1, 0),
  ('price-calamansi-250g-v1', 'sku-calamansi-250g', 'market-metro-cebu', 'STANDARD', 'PHP', 2975, 0, 1, 0),
  ('price-calamansi-500g-v1', 'sku-calamansi-500g', 'market-metro-cebu', 'STANDARD', 'PHP', 5950, 0, 1, 0),
  ('price-calamansi-1kg-v1', 'sku-calamansi-1kg', 'market-metro-cebu', 'STANDARD', 'PHP', 11900, 0, 1, 0),
  ('price-papaya-250g-v1', 'sku-papaya-250g', 'market-metro-cebu', 'STANDARD', 'PHP', 4375, 0, 1, 0),
  ('price-papaya-500g-v1', 'sku-papaya-500g', 'market-metro-cebu', 'STANDARD', 'PHP', 8750, 0, 1, 0),
  ('price-papaya-1kg-v1', 'sku-papaya-1kg', 'market-metro-cebu', 'STANDARD', 'PHP', 17500, 0, 1, 0),
  ('price-tomato-250g-v1', 'sku-tomato-250g', 'market-metro-cebu', 'STANDARD', 'PHP', 3225, 0, 1, 0),
  ('price-tomato-500g-v1', 'sku-tomato-500g', 'market-metro-cebu', 'STANDARD', 'PHP', 6450, 0, 1, 0),
  ('price-tomato-1kg-v1', 'sku-tomato-1kg', 'market-metro-cebu', 'STANDARD', 'PHP', 12900, 0, 1, 0),
  ('price-carrot-250g-v1', 'sku-carrot-250g', 'market-metro-cebu', 'STANDARD', 'PHP', 3475, 0, 1, 0),
  ('price-carrot-500g-v1', 'sku-carrot-500g', 'market-metro-cebu', 'STANDARD', 'PHP', 6950, 0, 1, 0),
  ('price-carrot-1kg-v1', 'sku-carrot-1kg', 'market-metro-cebu', 'STANDARD', 'PHP', 13900, 0, 1, 0),
  ('price-broccoli-250g-v1', 'sku-broccoli-250g', 'market-metro-cebu', 'STANDARD', 'PHP', 5450, 0, 1, 0),
  ('price-broccoli-500g-v1', 'sku-broccoli-500g', 'market-metro-cebu', 'STANDARD', 'PHP', 10900, 0, 1, 0),
  ('price-broccoli-1kg-v1', 'sku-broccoli-1kg', 'market-metro-cebu', 'STANDARD', 'PHP', 21800, 0, 1, 0),
  ('price-cucumber-250g-v1', 'sku-cucumber-250g', 'market-metro-cebu', 'STANDARD', 'PHP', 3825, 0, 1, 0),
  ('price-cucumber-500g-v1', 'sku-cucumber-500g', 'market-metro-cebu', 'STANDARD', 'PHP', 7650, 0, 1, 0),
  ('price-cucumber-1kg-v1', 'sku-cucumber-1kg', 'market-metro-cebu', 'STANDARD', 'PHP', 15300, 0, 1, 0),
  ('price-cabbage-250g-v1', 'sku-cabbage-250g', 'market-metro-cebu', 'STANDARD', 'PHP', 2925, 0, 1, 0),
  ('price-cabbage-500g-v1', 'sku-cabbage-500g', 'market-metro-cebu', 'STANDARD', 'PHP', 5850, 0, 1, 0),
  ('price-cabbage-1kg-v1', 'sku-cabbage-1kg', 'market-metro-cebu', 'STANDARD', 'PHP', 11700, 0, 1, 0),
  ('price-eggplant-250g-v1', 'sku-eggplant-250g', 'market-metro-cebu', 'STANDARD', 'PHP', 3425, 0, 1, 0),
  ('price-eggplant-500g-v1', 'sku-eggplant-500g', 'market-metro-cebu', 'STANDARD', 'PHP', 6850, 0, 1, 0),
  ('price-eggplant-1kg-v1', 'sku-eggplant-1kg', 'market-metro-cebu', 'STANDARD', 'PHP', 13700, 0, 1, 0),
  ('price-kangkong-250g-v1', 'sku-kangkong-250g', 'market-metro-cebu', 'STANDARD', 'PHP', 2475, 0, 1, 0),
  ('price-kangkong-500g-v1', 'sku-kangkong-500g', 'market-metro-cebu', 'STANDARD', 'PHP', 4950, 0, 1, 0),
  ('price-kangkong-1kg-v1', 'sku-kangkong-1kg', 'market-metro-cebu', 'STANDARD', 'PHP', 9900, 0, 1, 0),
  ('price-pechay-250g-v1', 'sku-pechay-250g', 'market-metro-cebu', 'STANDARD', 'PHP', 2725, 0, 1, 0),
  ('price-pechay-500g-v1', 'sku-pechay-500g', 'market-metro-cebu', 'STANDARD', 'PHP', 5450, 0, 1, 0),
  ('price-pechay-1kg-v1', 'sku-pechay-1kg', 'market-metro-cebu', 'STANDARD', 'PHP', 10900, 0, 1, 0),
  ('price-garlic-250g-v1', 'sku-garlic-250g', 'market-metro-cebu', 'STANDARD', 'PHP', 6450, 0, 1, 0),
  ('price-garlic-500g-v1', 'sku-garlic-500g', 'market-metro-cebu', 'STANDARD', 'PHP', 12900, 0, 1, 0),
  ('price-garlic-1kg-v1', 'sku-garlic-1kg', 'market-metro-cebu', 'STANDARD', 'PHP', 25800, 0, 1, 0);

INSERT OR IGNORE INTO location_product_availability
  (location_id, product_id, availability_status, sourcing_mode, valid_from)
VALUES
  ('location-cebu-central', 'product-avocado', 'AVAILABLE', 'HYBRID', 0),
  ('location-cebu-central', 'product-banana-lakatan', 'AVAILABLE', 'HYBRID', 0),
  ('location-cebu-central', 'product-mango-carabao', 'AVAILABLE', 'HYBRID', 0),
  ('location-cebu-central', 'product-strawberry', 'AVAILABLE', 'HYBRID', 0),
  ('location-cebu-central', 'product-pineapple', 'AVAILABLE', 'HYBRID', 0),
  ('location-cebu-central', 'product-watermelon', 'AVAILABLE', 'HYBRID', 0),
  ('location-cebu-central', 'product-calamansi', 'AVAILABLE', 'HYBRID', 0),
  ('location-cebu-central', 'product-papaya', 'AVAILABLE', 'HYBRID', 0),
  ('location-cebu-central', 'product-tomato', 'AVAILABLE', 'HYBRID', 0),
  ('location-cebu-central', 'product-carrot', 'AVAILABLE', 'HYBRID', 0),
  ('location-cebu-central', 'product-broccoli', 'AVAILABLE', 'HYBRID', 0),
  ('location-cebu-central', 'product-cucumber', 'AVAILABLE', 'HYBRID', 0),
  ('location-cebu-central', 'product-cabbage', 'AVAILABLE', 'HYBRID', 0),
  ('location-cebu-central', 'product-eggplant', 'AVAILABLE', 'HYBRID', 0),
  ('location-cebu-central', 'product-kangkong', 'AVAILABLE', 'HYBRID', 0),
  ('location-cebu-central', 'product-pechay', 'AVAILABLE', 'HYBRID', 0),
  ('location-cebu-central', 'product-garlic', 'AVAILABLE', 'HYBRID', 0);
