-- Generated by scripts/generate-promotion-benefits-migration.mjs from the 0084 baseline.

-- Preserve every affected row/rowid, index and historical snapshot. No database reset or storage calls.

-- Legacy DELIVERY_FEE_DISCOUNT remains valid in historical evidence; live definitions use the explicit percentage type.

PRAGMA defer_foreign_keys=ON;

CREATE TABLE "schema_0085_checkout_promotion_claim" AS SELECT rowid AS schema_original_rowid,* FROM "checkout_promotion_claim";

CREATE TABLE "schema_0085_order_promotion_application" AS SELECT rowid AS schema_original_rowid,* FROM "order_promotion_application";

CREATE TABLE "schema_0085_promotion" AS SELECT rowid AS schema_original_rowid,* FROM "promotion";

CREATE TABLE "schema_0085_promotion_grant" AS SELECT rowid AS schema_original_rowid,* FROM "promotion_grant";

CREATE TABLE "schema_0085_promotion_redemption" AS SELECT rowid AS schema_original_rowid,* FROM "promotion_redemption";

CREATE TABLE "schema_0085_promotion_rule" AS SELECT rowid AS schema_original_rowid,* FROM "promotion_rule";

DROP TABLE "checkout_promotion_claim";

DROP TABLE "order_promotion_application";

DROP TABLE "promotion_redemption";

DROP TABLE "promotion_grant";

DROP TABLE "promotion_rule";

DROP TABLE "promotion";

CREATE TABLE "checkout_promotion_claim" (
  id TEXT NOT NULL PRIMARY KEY,
  checkout_quote_id TEXT NOT NULL REFERENCES checkout_quote(id) ON DELETE CASCADE,
  promotion_id TEXT NOT NULL REFERENCES promotion(id),
  customer_id TEXT NOT NULL REFERENCES customer(id),
  price_component TEXT NOT NULL CHECK (price_component IN ('MERCHANDISE', 'DELIVERY')),
  benefit_type TEXT NOT NULL CHECK (benefit_type IN (
    'ORDER_FIXED_DISCOUNT', 'ORDER_PERCENT_DISCOUNT',
    'DELIVERY_FEE_WAIVER', 'DELIVERY_FEE_DISCOUNT','DELIVERY_PERCENT_DISCOUNT','DELIVERY_FIXED_DISCOUNT'
  )),
  amount_minor INTEGER NOT NULL CHECK (amount_minor >= 0),
  definition_version INTEGER NOT NULL CHECK (definition_version >= 1),
  grant_id TEXT REFERENCES promotion_grant(id),
  snapshot_json TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'UNCOMMITTED' CHECK (status IN ('UNCOMMITTED', 'COMMITTED')),
  created_at INTEGER NOT NULL,
  committed_at INTEGER,
  UNIQUE(checkout_quote_id, promotion_id, price_component)
,
  CHECK ("amount_minor" IS NULL OR "amount_minor" BETWEEN -9007199254740991 AND 9007199254740991),
  CHECK ("definition_version" IS NULL OR "definition_version" BETWEEN -9007199254740991 AND 9007199254740991),
  CHECK ("created_at" IS NULL OR "created_at" BETWEEN -9007199254740991 AND 9007199254740991),
  CHECK ("committed_at" IS NULL OR "committed_at" BETWEEN -9007199254740991 AND 9007199254740991)
) STRICT;

CREATE TABLE "order_promotion_application" (
  id TEXT NOT NULL PRIMARY KEY,
  order_id TEXT NOT NULL REFERENCES grocery_order(id) ON DELETE CASCADE,
  amendment_id TEXT,
  promotion_id TEXT NOT NULL REFERENCES promotion(id),
  redemption_id TEXT NOT NULL REFERENCES promotion_redemption(id),
  price_component TEXT NOT NULL CHECK (price_component IN ('MERCHANDISE', 'DELIVERY')),
  benefit_type TEXT NOT NULL,
  amount_minor INTEGER NOT NULL CHECK (amount_minor >= 0),
  benefit_snapshot_json TEXT NOT NULL,
  created_at INTEGER NOT NULL
,
  CHECK ("amount_minor" IS NULL OR "amount_minor" BETWEEN -9007199254740991 AND 9007199254740991),
  CHECK ("created_at" IS NULL OR "created_at" BETWEEN -9007199254740991 AND 9007199254740991)
) STRICT;

CREATE TABLE "promotion" (
  id TEXT NOT NULL PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL CHECK (status IN ('DRAFT', 'ACTIVE', 'INACTIVE', 'ARCHIVED')),
  benefit_type TEXT NOT NULL CHECK (benefit_type IN ('ORDER_FIXED_DISCOUNT', 'ORDER_PERCENT_DISCOUNT', 'DELIVERY_FEE_WAIVER', 'DELIVERY_FEE_DISCOUNT','DELIVERY_PERCENT_DISCOUNT','DELIVERY_FIXED_DISCOUNT')),
  discount_minor INTEGER,
  percent INTEGER,
  minimum_minor INTEGER NOT NULL DEFAULT 0,
  starts_at INTEGER NOT NULL,
  ends_at INTEGER,
  global_usage_limit INTEGER,
  per_customer_usage_limit INTEGER,
  automatic INTEGER NOT NULL DEFAULT 0,
  priority INTEGER NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 1,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  maximum_discount_minor INTEGER
  CHECK (maximum_discount_minor IS NULL OR maximum_discount_minor >= 0),
  CHECK (benefit_type != 'ORDER_FIXED_DISCOUNT' OR discount_minor IS NOT NULL),
  CHECK (benefit_type != 'ORDER_PERCENT_DISCOUNT' OR percent IS NOT NULL)
,
  CHECK ("discount_minor" IS NULL OR "discount_minor" BETWEEN -9007199254740991 AND 9007199254740991),
  CHECK ("percent" IS NULL OR "percent" BETWEEN -9007199254740991 AND 9007199254740991),
  CHECK ("minimum_minor" IS NULL OR "minimum_minor" BETWEEN -9007199254740991 AND 9007199254740991),
  CHECK ("starts_at" IS NULL OR "starts_at" BETWEEN -9007199254740991 AND 9007199254740991),
  CHECK ("ends_at" IS NULL OR "ends_at" BETWEEN -9007199254740991 AND 9007199254740991),
  CHECK ("global_usage_limit" IS NULL OR "global_usage_limit" BETWEEN -9007199254740991 AND 9007199254740991),
  CHECK ("per_customer_usage_limit" IS NULL OR "per_customer_usage_limit" BETWEEN -9007199254740991 AND 9007199254740991),
  CHECK ("automatic" IS NULL OR "automatic" BETWEEN -9007199254740991 AND 9007199254740991),
  CHECK ("priority" IS NULL OR "priority" BETWEEN -9007199254740991 AND 9007199254740991),
  CHECK ("version" IS NULL OR "version" BETWEEN -9007199254740991 AND 9007199254740991),
  CHECK ("created_at" IS NULL OR "created_at" BETWEEN -9007199254740991 AND 9007199254740991),
  CHECK ("updated_at" IS NULL OR "updated_at" BETWEEN -9007199254740991 AND 9007199254740991),
  CHECK ("maximum_discount_minor" IS NULL OR "maximum_discount_minor" BETWEEN -9007199254740991 AND 9007199254740991)
) STRICT;

CREATE TABLE "promotion_grant" (
  id TEXT NOT NULL PRIMARY KEY,
  benefit_code TEXT NOT NULL,
  benefit_type TEXT NOT NULL CHECK (benefit_type IN ('MEMBERSHIP_FEE_WAIVER','ORDER_PERCENT_DISCOUNT','ORDER_FIXED_DISCOUNT','DELIVERY_FEE_WAIVER','DELIVERY_FEE_DISCOUNT','DELIVERY_PERCENT_DISCOUNT','DELIVERY_FIXED_DISCOUNT')),
  max_redemptions INTEGER NOT NULL DEFAULT 1 CHECK (max_redemptions >= 1),
  status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('DRAFT','ACTIVE','EXHAUSTED','REVOKED')),
  parameters_json TEXT NOT NULL DEFAULT '{}',
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  customer_id TEXT REFERENCES customer(id)
,
  CHECK ("max_redemptions" IS NULL OR "max_redemptions" BETWEEN -9007199254740991 AND 9007199254740991),
  CHECK ("created_at" IS NULL OR "created_at" BETWEEN -9007199254740991 AND 9007199254740991),
  CHECK ("updated_at" IS NULL OR "updated_at" BETWEEN -9007199254740991 AND 9007199254740991)
) STRICT;

CREATE TABLE "promotion_redemption" (
  id TEXT NOT NULL PRIMARY KEY,
  grant_id TEXT NOT NULL REFERENCES promotion_grant(id),
  benefit_code TEXT NOT NULL,
  benefit_type TEXT NOT NULL CHECK (benefit_type IN ('MEMBERSHIP_FEE_WAIVER','ORDER_PERCENT_DISCOUNT','ORDER_FIXED_DISCOUNT','DELIVERY_FEE_WAIVER','DELIVERY_FEE_DISCOUNT','DELIVERY_PERCENT_DISCOUNT','DELIVERY_FIXED_DISCOUNT')),
  customer_id TEXT NOT NULL REFERENCES customer(id),
  subject_type TEXT,
  subject_id TEXT,
  redeemed_at INTEGER NOT NULL,
  promotion_id TEXT REFERENCES promotion(id),
  order_id TEXT REFERENCES grocery_order(id),
  amendment_id TEXT,
  price_component TEXT
  CHECK (price_component IS NULL OR price_component IN ('MEMBERSHIP', 'MERCHANDISE', 'DELIVERY')),
  amount_minor INTEGER
  CHECK (amount_minor IS NULL OR amount_minor >= 0),
  benefit_snapshot_json TEXT,
  eligibility_snapshot_json TEXT,
  idempotency_key TEXT
,
  CHECK ("redeemed_at" IS NULL OR "redeemed_at" BETWEEN -9007199254740991 AND 9007199254740991),
  CHECK ("amount_minor" IS NULL OR "amount_minor" BETWEEN -9007199254740991 AND 9007199254740991)
) STRICT;

CREATE TABLE "promotion_rule" (
  id TEXT NOT NULL PRIMARY KEY,
  promotion_id TEXT NOT NULL REFERENCES promotion(id) ON DELETE CASCADE,
  rule_type TEXT NOT NULL CHECK (rule_type IN (
    'FIRST_ORDER', 'NEW_CUSTOMER', 'MEMBER', 'NON_MEMBER',
    'MINIMUM_SUBTOTAL', 'CUSTOMER_SEGMENT', 'SPECIFIC_CUSTOMERS'
  )),
  parameters_json TEXT NOT NULL DEFAULT '{}',
  sort_order INTEGER NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 1 CHECK (version >= 1),
  created_at INTEGER NOT NULL DEFAULT 0,
  updated_at INTEGER NOT NULL DEFAULT 0
,
  CHECK ("sort_order" IS NULL OR "sort_order" BETWEEN -9007199254740991 AND 9007199254740991),
  CHECK ("version" IS NULL OR "version" BETWEEN -9007199254740991 AND 9007199254740991),
  CHECK ("created_at" IS NULL OR "created_at" BETWEEN -9007199254740991 AND 9007199254740991),
  CHECK ("updated_at" IS NULL OR "updated_at" BETWEEN -9007199254740991 AND 9007199254740991)
) STRICT;

INSERT INTO "checkout_promotion_claim" (rowid,"id","checkout_quote_id","promotion_id","customer_id","price_component","benefit_type","amount_minor","definition_version","grant_id","snapshot_json","status","created_at","committed_at") SELECT schema_original_rowid,"id","checkout_quote_id","promotion_id","customer_id","price_component","benefit_type","amount_minor","definition_version","grant_id","snapshot_json","status","created_at","committed_at" FROM "schema_0085_checkout_promotion_claim";

INSERT INTO "order_promotion_application" (rowid,"id","order_id","amendment_id","promotion_id","redemption_id","price_component","benefit_type","amount_minor","benefit_snapshot_json","created_at") SELECT schema_original_rowid,"id","order_id","amendment_id","promotion_id","redemption_id","price_component","benefit_type","amount_minor","benefit_snapshot_json","created_at" FROM "schema_0085_order_promotion_application";

INSERT INTO "promotion" (rowid,"id","code","name","description","status","benefit_type","discount_minor","percent","minimum_minor","starts_at","ends_at","global_usage_limit","per_customer_usage_limit","automatic","priority","version","created_at","updated_at","maximum_discount_minor") SELECT schema_original_rowid,"id","code","name","description","status","benefit_type","discount_minor","percent","minimum_minor","starts_at","ends_at","global_usage_limit","per_customer_usage_limit","automatic","priority","version","created_at","updated_at","maximum_discount_minor" FROM "schema_0085_promotion";

INSERT INTO "promotion_grant" (rowid,"id","benefit_code","benefit_type","max_redemptions","status","parameters_json","created_at","updated_at","customer_id") SELECT schema_original_rowid,"id","benefit_code","benefit_type","max_redemptions","status","parameters_json","created_at","updated_at","customer_id" FROM "schema_0085_promotion_grant";

INSERT INTO "promotion_redemption" (rowid,"id","grant_id","benefit_code","benefit_type","customer_id","subject_type","subject_id","redeemed_at","promotion_id","order_id","amendment_id","price_component","amount_minor","benefit_snapshot_json","eligibility_snapshot_json","idempotency_key") SELECT schema_original_rowid,"id","grant_id","benefit_code","benefit_type","customer_id","subject_type","subject_id","redeemed_at","promotion_id","order_id","amendment_id","price_component","amount_minor","benefit_snapshot_json","eligibility_snapshot_json","idempotency_key" FROM "schema_0085_promotion_redemption";

INSERT INTO "promotion_rule" (rowid,"id","promotion_id","rule_type","parameters_json","sort_order","version","created_at","updated_at") SELECT schema_original_rowid,"id","promotion_id","rule_type","parameters_json","sort_order","version","created_at","updated_at" FROM "schema_0085_promotion_rule";

CREATE INDEX checkout_promotion_claim_definition_idx
  ON checkout_promotion_claim(promotion_id, status);

CREATE UNIQUE INDEX order_promotion_application_benefit_unique ON order_promotion_application(order_id,IFNULL(amendment_id,''),promotion_id,price_component);

CREATE UNIQUE INDEX order_promotion_application_redemption_unique ON order_promotion_application(redemption_id);

CREATE UNIQUE INDEX promotion_grant_promotion_customer_unique
  ON promotion_grant(benefit_code, customer_id)
  WHERE customer_id IS NOT NULL;

CREATE INDEX promotion_grant_status_idx
  ON promotion_grant(status, benefit_code);

CREATE INDEX promotion_redemption_customer_idx
  ON promotion_redemption(customer_id, redeemed_at);

CREATE INDEX promotion_redemption_definition_customer_idx
  ON promotion_redemption(promotion_id, customer_id, redeemed_at);

CREATE UNIQUE INDEX promotion_redemption_idempotency_unique
  ON promotion_redemption(idempotency_key) WHERE idempotency_key IS NOT NULL;

CREATE UNIQUE INDEX promotion_redemption_one_intro_trial_per_customer_idx
  ON promotion_redemption(benefit_code, customer_id)
  WHERE benefit_code = 'INTRO_TRIAL';

CREATE INDEX promotion_rule_definition_idx
  ON promotion_rule(promotion_id, sort_order, id);

CREATE INDEX promotion_status_idx ON promotion(status, starts_at);

UPDATE promotion SET benefit_type='DELIVERY_PERCENT_DISCOUNT',version=version+1 WHERE benefit_type='DELIVERY_FEE_DISCOUNT';

DROP TABLE "schema_0085_checkout_promotion_claim";

DROP TABLE "schema_0085_order_promotion_application";

DROP TABLE "schema_0085_promotion";

DROP TABLE "schema_0085_promotion_grant";

DROP TABLE "schema_0085_promotion_redemption";

DROP TABLE "schema_0085_promotion_rule";
