/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=tests/wrangler.provider-gateway.jsonc --include-runtime=false --env-interface=BrowserGatewayEnv tests/provider-gateway-env.d.ts` (hash: a3ce2cf8d9d7fea40d61bc26541e224c)
interface __BaseEnv_BrowserGatewayEnv {
  WEB: Fetcher /* freshmarkets-web */;
  PAYMENT_WEBHOOK: Fetcher /* freshmarkets-core */;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./provider-gateway");
  }
  interface Env extends __BaseEnv_BrowserGatewayEnv {}
}
interface BrowserGatewayEnv extends __BaseEnv_BrowserGatewayEnv {}
